[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_error.js.map"
    [headers.values]
    Content-Type = "application/json"
